POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"prueba",
    "email":"casa@gmail.com",
    "password":"123456"

}



### login 

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json 

{
    "name":"prueba",
    "email":"casa@gmail.com",
    "password":"123456"

}

###users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzI3NDgwNjIsImV4cCI6MTczMjc0ODEyMn0.kB13CVTaP1KNSfoQ-ke0v7wA31er2lbFhvz5cnUfSII